### ISSUE TITLE
[Epic] AST optimizations

### ISSUE THREAD

**Issue by effectfully** [IntersectMBO/plutus#5967]
This issue is for dumping all the plans regarding AST optimizations (such as case-of-case, case-of-known-constructors etc) in a largely unstructured way. We'll have separate messages for Plutus Core and Plutus IR, please just edit those instead of creating more messages.

**Comment by effectfully** [comment]
## Untyped Plutus Core

- [ ] regarding order of effects, we should figure out a strategy for when it's fine to change it and when it's not. It's worth handling logging and bottom separately, since messing with the former is OK (given it's locked behind a flag not enabled by default) and messing with the latter is a no-no
- [ ] I saw `((\cse -> case cse [cse]) error)`, we should rewrite this to just `error`
- [ ] we need a test that the inliner inline `blah` in `(\b -> force ifThenElse b branch1 branch2) blah`. If it doesn't, we should implement that functionality
- [ ] handle `chooseList` in case-of-case similarly to `ifThenElse`?
- [ ] Aiken folks gave us an idea: try replacing Scott-encoded tuples with SOP-encoded tuples in the recursive functions combinators, SOP-encoded tuples should be faster thus making mutual recursion faster. If there’s anything else Scott-encoded there, we should change it too. Perhaps we could update the entire `PlutusCore.StdLib.Meta.Data.Tuple`. We have to keep the old code too for older versions of Plutus
- [ ] both UPLC and PIR have `termEvaluationOrder` defined for them which goes into "known function body" in case of `Apply` (see the logic there) and goes into "known delayed term" for `Force`, but does not go into "known branch" for `Constr`
- [ ] both UPLC and PIR have `termEvaluationOrder` defined for them which does into "known delayed term" for `Force` and considers that to be `MaybeWork`. Is it work though? It literally has to be optimized away, do we want to prevent some optimization from firing just because there's an immediately `Force`d `Delay`? This should at least be discussed in a Note
- [ ] we sometimes generate things like `force (force (force ifThenElse b (delay (delay x)) (delay (delay y))))`. Surely we can turn double-force-delays into single force-delays?
- [ ] “Outer let-floating” for UPLC is considered to be moving `(\x1...xn -> body) t1 ... tn` outside of a context. We have investigated the case where the context is force, [this comment](https://github.com/IntersectMBO/plutus/pull/5799#discussion_r1526456121) should argue why I believe that for proper force-delay cancellation we need to implement something more specialised, as is done in the PR. This is for investigating other contexts: `<context> ((\x1 ... xn -> body) t1 ... tn)`.
- [ ] `(((\a b c -> a + b + c) 10) 20) 30` is more expensive than `(case (constr 0 [10, 20, 30]) f)` given we apply more than 3 arguments, so we can have transform that converts chained applications into this form.  [This](https://github.com/Plutonomicon/plutarch-plutus/blob/fd7d1c1fc173542f952f19272554027183659dd6/Plutarch/Internal/Term.hs#L705-L723
) is one way of implementing it, but this could be simpler since this deals with some other stuff as well (I read somewhere `ApplyN` is planned, so once we have that this will be outdated. Though, I think this transformer is simple and good to have enough till than)
- [ ] force-delay knows how to look under applications, but force-case-delay [doesn't](https://github.com/IntersectMBO/plutus/pull/7231#discussion_r2241334227). We should just shove those into a singe optimization to avoid reimplementing the same tricks

**Comment by effectfully** [comment]
## Plutus IR

**Comment by effectfully** [comment]
## Plutus Tx 

- [ ] Add `Lazy` and use it throughout Plutus Tx code instead of the slower `()`  (extricated from #6060)
