### ISSUE TITLE
[Epic] Sort out structural vs operational evaluation errors

### ISSUE THREAD

**Issue by effectfully** [IntersectMBO/plutus#6150]
We have two kinds of evaluation errors: structural ones and operational ones. More on that [here](https://github.com/IntersectMBO/plutus/blob/b61cce8a4c0f598dacaf531a47c00bfc9ce33e72/plutus-core/plutus-core/src/PlutusCore/Evaluation/Error.hs#L30-L56). This issue is for dumping all the things that we could improve upon in this context.

**Comment by effectfully** [comment]
- [ ] `EvaluationError operational structural` is backwards, `structural` should come first as structural errors concern how the program is constructed, whiich obviously precedes evaluation, which is what operational errors are about
- [ ] there is no test like "evaluating a well-typed program never results in a structural error". In general there are no explicit tests on this whole structural vs operational distinction (we do have some implicit ones, but that's not nearly enough)
- [ ] the content of an operational unlifting error is erased by the CK/CEK machine, so the error message never reaches the user. "Something went wrong" is a horrible thing to display to the user, we should do better (at least we print the offending term though)
- [ ] builtin denotations don't distinguish between the two kinds of errors and just pretend that every builtin error is an operational one, which is not the case for `headList` for example: while `headList []` should give an operational error, the "ill-typed" `headList True` should give a structural one
