### ISSUE TITLE
[Epic] Tests improvements

### ISSUE THREAD

**Issue by effectfully** [IntersectMBO/plutus#6608]
This issue is for dumping all the plans regarding tests improvements in a largely unstructured way.

**Comment by effectfully** [comment]
- [x] `discardIfAnyConstant (not . isSerialisable) $ Generators.genProgram @DefaultFun` potentially wastes a lot of time discarding generated programs. `discardIfAnyConstant` is used in quite a few places
- [ ] `Evaluation.Builtins.Definition` should demand that each built-in function is unit-tested
- [ ] remove `ignoreTest` from Plutus IR tests by fixing the tests
- [ ] increase the number of test runs in Plutus IR from no to some (i.e. fix `withMaxSuccess 0`) for failing shrinking tests by figuring out why they are taking too long and fixing that
- [ ] can we somehow ban running 100 tests altogether? So that the number of tests to run is always explicitly specified
